{% set name = "folly" %}
{% set version = "2018.05.07.00" %}
{% set sha256 = "d3d5b653070bd21e8b1f0bfc26a28bb0948fd6d81a5db67bed60659e9dabb547" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/facebook/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }} >=5
    - gtest
    - boost
    - cmake
    - automake
    - boost-cpp
    - libtool
    - lz4
    - backports.lzma
    - snappy
    - zlib
    - glog
    - gflags
    - scons
    - openssl
    - libevent
    - libunwind
    - toolchain
    - double-conversion
    - pkg-config

about:
  home: https://github.com/facebook/folly/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'An open-source C++ library developed and used at Facebook.'

  description: |
    Folly (acronymed loosely after Facebook Open Source Library) is a library of C++11 components 
    designed with practicality and efficiency in mind. Folly contains a variety of core library 
    components used extensively at Facebook. In particular, it's often a dependency of Facebook's 
    other open source C++ efforts and place where those projects can share code.
  doc_url: https://github.com/facebook/folly
  dev_url: https://github.com/facebook/folly

extra:
  recipe-maintainers:
    - xmnlab
