{% set name = "cudatoolkit" %}
{% set major_version = "9.2" %}
{% set minor_version = "88_396.26"%}
{% set sha256 = "8d02cc2a82f35b456d447df463148ac4cc823891be8820948109ad6186f2667c" %}
{% set filename = "cuda_" + major_version + "." +  minor_version + "_linux" %}

package:
  name: {{ name|lower }}
  version: {{ major_version }}.{{ minor_version }}

#source:
#  path: /home/dev/var/cudatoolkit-9_0-x86_64/build/scripts

source:
  fn: {{ filename }}
  url: https://developer.nvidia.com/compute/cuda/{{ major_version }}/Prod/local_installers/{{ filename }}
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python >=3
    - requests
    - conda
    - pyyaml
    - wget

test:
  requires:
    - numba

about:
  home: https://developer.nvidia.com
  license: other
  license_family: other
  license_file: '{{ environ["RECIPE_DIR"] }}/EULA.pdf'
  summary: 'Develop, Optimize and Deploy GPU-accelerated Apps'
  description: |
    The NVIDIA CUDA Toolkit provides a development environment for creating 
    high performance GPU-accelerated applications. With the CUDA Toolkit, 
    you can develop, optimize and deploy your applications on GPU-accelerated
    embedded systems, desktop workstations, enterprise data centers, 
    cloud-based platforms and HPC supercomputers. The toolkit includes 
    GPU-accelerated libraries, debugging and optimization tools, 
    a C/C++ compiler and a runtime library to deploy your application.
    This package just have some binaries from the full package. 
  doc_url: https://developer.nvidia.com/cuda-toolkit
  dev_url: https://developer.nvidia.com/cuda-toolkit

extra:
  recipe-maintainers:
    - xmnlab
    - scopatz
    - andersy005
